msg: '&a[%server%] %player% executed %cmd%'
hiddenCmds:
  - '/l '
  - '/log '
  - '/login'
  - /reg
  - /changepass
  - /cp
  - '/tell '
  - '/msg '
  - /pm
  - /pmsg
  - '/w '
  - /m
  - /whisper
  - /LOGIN
  - '/r '
ignoreCase: true
reloadMsg: "&aConfig reloaded!"
